import { Router } from 'express';
import cartController from '~/controllers/cart.controller';
import { authMiddleware } from '~/middlewares/auth.middleware';
const { authentication } = authMiddleware;
const router = Router();
router.post('/add-to-cart', authentication, cartController.addToCart);
router.put('/update-quantity/:id', authentication, cartController.updateQuantity);
router.delete('/remove-product', authentication, cartController.removeProduct);
router.get('/get-detail/:id', authentication, cartController.getDetail);
export const cartRouter = router;
